<b><font size="5">Import relevant libraries and dataframes</font><a class="anchor"><a id='toc'></a></b>

In [1]:
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
import numpy as np
import warnings
warnings.simplefilter("ignore")
from sklearn.cluster import KMeans
from scipy.cluster.hierarchy import dendrogram, linkage
from sklearn.preprocessing import MinMaxScaler

In [6]:
wm_cleaned = pd.read_csv(r'data\WineMatters_cleaned.csv')
wm_cleaned.set_index('WineID', inplace = True)
wm_cleaned.head()

,Aging_Time,Litters_Barrel,Magnesium,Residual_Sugar,Acidity,Floral,Wood,Sweetness,Red_Fruit,Citric,...,Alcohol,Astringency,Satisfaction_France,Satisfaction_Spain,Satisfaction_Portugal,Sulphites_Presence,Type_White,Barrel_Wooden,Grapes_Single,Satisfaction_General
WineID,,,,,,,,,,,,,,,,,,,,,
1,65,265,0,0.0,0,5,0,2,2,4,...,0,0,3,3,2,0,1,0,1,1
2,47,2464,310,305.0,4,2,0,3,0,2,...,0,0,4,3,2,1,0,0,1,1
3,15,2138,0,0.0,3,4,0,3,2,0,...,0,0,4,4,2,0,1,0,1,1
4,60,623,0,0.0,0,4,0,3,3,4,...,0,0,1,1,3,0,1,0,1,0
5,70,354,0,0.0,0,4,0,3,4,3,...,0,0,2,2,5,0,1,0,1,1

In [3]:
wm_scaled = pd.read_csv(r'data\WineMatters_scaled.csv')
wm_scaled.head()

,Unnamed: 0,Aging_Time,Litters_Barrel,Magnesium,Residual_Sugar,Acidity,Floral,Wood,Sweetness,Red_Fruit,...,Cloudiness,Alcohol,Astringency,Satisfaction_France,Satisfaction_Spain,Satisfaction_Portugal,Sulphites_Presence,Type_White,Barrel_Wooden,Grapes_Single
0,1,0.743590,0.034003,0.000000,0.000000,0.0,5.0,0.0,2.0,2.0,...,3.0,0.0,0.0,3.0,3.0,2.0,0.0,1.0,0.0,1.0
1,2,0.512821,0.381781,0.707763,0.693182,4.0,2.0,0.0,3.0,0.0,...,4.0,0.0,0.0,4.0,3.0,2.0,1.0,0.0,0.0,1.0
2,3,0.102564,0.330223,0.000000,0.000000,3.0,4.0,0.0,3.0,2.0,...,3.0,0.0,0.0,4.0,4.0,2.0,0.0,1.0,0.0,1.0
3,4,0.679487,0.090622,0.000000,0.000000,0.0,4.0,0.0,3.0,3.0,...,1.0,0.0,0.0,1.0,1.0,3.0,0.0,1.0,0.0,1.0
4,5,0.807692,0.048078,0.000000,0.000000,0.0,4.0,0.0,3.0,4.0,...,2.0,0.0,0.0,2.0,2.0,5.0,0.0,1.0,0.0,1.0

In [7]:
wm_flavfeel = pd.read_csv(r'data\WineMatters_flavfeel.csv')
wm_flavfeel.set_index('WineID', inplace = True)
wm_flavfeel.head()

,Residual_Sugar,Acidity,Floral,Wood,Sweetness,Red_Fruit,Citric,Density,Cloudiness,Alcohol,Astringency
WineID,,,,,,,,,,,
1,0.0,0,5,0,2,2,4,2,3,0,0
2,305.0,4,2,0,3,0,2,2,4,0,0
3,0.0,3,4,0,3,2,0,2,3,0,0
4,0.0,0,4,0,3,3,4,3,1,0,0
5,0.0,0,4,0,3,4,3,4,2,0,0

In [8]:
wm_prodchar = pd.read_csv(r'data\WineMatters_prodchar.csv')
wm_prodchar.set_index('WineID', inplace = True)
wm_prodchar.head()

,Aging_Time,Litters_Barrel,Type_White,Magnesium,Sulphites_Presence,Barrel_Wooden,Grapes_Single,Color_Intensity
WineID,,,,,,,,
1,65,265,1,0,0,0,1,3
2,47,2464,0,310,1,0,1,3
3,15,2138,1,0,0,0,1,2
4,60,623,1,0,0,0,1,1
5,70,354,1,0,0,0,1,2

<b><font size="5">SOM - wm_flavfeel</font><a class="anchor"><a id='toc'></a></b>